### ISSUE TITLE
Sticky header that doesn't get removed on scmp.com

### ISSUE THREAD

**Issue by dellistic** [lykahb/sticky-ducky#11]
Just highlight that the sticky header at scmp.com doesn't get removed by sticky ducky.

Example URL:
https://www.scmp.com/lifestyle/entertainment/article/3042761/bruce-lees-story-next-us-says-ip-man-4-producer-donnie-yen

**Comment by lykahb** [comment]
Thank you for the report. That page has an interesting layout. What looks like a sticky header is a static element on top. The article is scrolled inside of another element below. You can see that because the scrollbar does not extend as high as the header. Sticky Ducky or any similar extension won't be able to clean that up.
