### ISSUE TITLE
Feature Request: Easier way to whitelist a site

### ISSUE THREAD

**Issue by HubKing** [lykahb/sticky-ducky#15]
This extension is useful, but in my experience, it often undesirably hides some sticky elements that should not be hidden. There is a whitelist feature, but it is not that convenient. I have to click the [Settings], type the site's URL, and click save.

An extension like Dark Reader has an easier method. It automatically detects and shows the current domain, and just clicking the domain name whitelists the domain. I wish Sticky Ducky would have the same method to whitelist a site.

**Comment by lykahb** [comment]
That's a good idea. Also, can you share a few examples where it hides the elements that should remain?

**Comment by lykahb** [comment]
Released this feature in the version 1.7. Please open another issue with websites where Sticky Ducky hides more than it should.

**Comment by HubKing** [comment]
Thanks. About the unwanted hidings, maybe it is not programmatically discernible whether something should be hidden or not. Humans know what is need or not, but that cannot be easily determined by code.

For example, there is a famous Korean online shopping site, [emart](http://emart.ssg.com). It has the [shopping cart page](https://pay.ssg.com/), and the screenshot below is before scrolling.

![image](https://user-images.githubusercontent.com/10900489/108571656-ff70e280-7353-11eb-8ca9-ff68d9d92eea.png)

And if I try to scroll the page (to see more items in the cart), it becomes like this

![image](https://user-images.githubusercontent.com/10900489/108571794-46f76e80-7354-11eb-967b-a710fbfa6e38.png)

On the right side, the summation and the proceed to check-out box is hidden, and that place becomes empty.

Since, now whitelisting became easy, I will just whitelist sites whenever I encounter such problems.

PS: It seems that the button is not a toggle (add to whitelist/remove from whitelist). Wouldn't it be more convenient if it was a toggle button?

**Comment by lykahb** [comment]
So, the shopping cart is hidden because Sticky Ducky recognizes it as a widget - a small rectangle. The widgets are often used for "contact us", chat, newsletter subscription, or other junk. They are seldom used in design for critical functionality of a page. The heuristics of sticky ducky is to show sidebars and full-size stickies (usually it's an image in a gallery). Here the shopping does not have enough height to be classified as a sidebar.

The text-based format under settings offers more detailed settings than just on/off. Making whitelist a toggle is possible but that's a lower priority than your last suggestion - it is easier to remove a line than add a line with a particular syntax.
